const GET_DOG = 'GET_DOG';
const FILTRO_CREACION = 'FILTRO_CREACION';
const GET_TEMPERAMENT ='GET_TEMPERAMENT';
const ORDEN_POR_NOMBRE = 'ORDEN_POR_NOMBRE';
const GET_NAME = 'GET_NAME'
const ORDEN_POR_PESO = 'ORDEN_POR_PESO'
const DAR_VUELTA = 'DAR_VUELTA'
const GET_NOTNAME ='GET_NOTNAME'
const POST_DOG = 'POST_DOG'
const DETALLES_DOG = 'DETALLES_DOG'
const FILTRO_TEMP = 'FILTRO_TEMP'

module.exports = {
  GET_DOG,
  FILTRO_CREACION,
  GET_TEMPERAMENT,
  ORDEN_POR_NOMBRE,
  GET_NAME,
  ORDEN_POR_PESO,
  DAR_VUELTA,
  GET_NOTNAME,
  POST_DOG,
  DETALLES_DOG,
  FILTRO_TEMP,
}